language: c
compiler: clang
branches:
    only:
        - ci
        - master
os:
    - linux
    - osx
sudo: false
dist: trusty
addons:
    apt:
        sources:
            - kubuntu-backports
        packages:
            - cmake
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
env:
    global:
        - CFLAGS=-Werror
    matrix:
        - BUILD_SHARED_LIBS=ON
        - BUILD_SHARED_LIBS=OFF
script:
    - if grep -Inr '\s$' src include docs deps tests examples CMake *.md .gitattributes .gitignore .github; then echo Trailing whitespace found, aborting.; exit 1; fi
    - mkdir build
    - cd build
    - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} ..
    - cmake --build .
notifications:
    email:
        recipients:
            - ci@glfw.org
    on_success: never
    on_failure: always
